version: "3.7"
services: 
  db:
    build:
      context: db
    environment:
      - MYSQL_DATABASE=testbase
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-mysql
    ports: 
      - "3306:3306"
    expose:
      - 3306
  backend:
    build:
      context: mybackend
      target: final
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend-backend
      - backend-mysql
    depends_on:
      - db
    ports:
      - "5293:5293"
    expose:
      - 5293
  frontend:
    build:
      context: myfrontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend-backend
    depends_on:
      - mybackend
    ports:
      - "8000:80"
    expose:
      - 80
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  frontend-backend: {}
  backend-mysql: {}